### ISSUE TITLE
Error when including variants with no RNA seq reads 

### ISSUE THREAD

**Issue by strixeh** [griffithlab/pVAC-Seq#207]
Hi,

I am running the pipeline with bam-readcounts but I get an error (see below). I think I have located the error: when a location in the VCF (chr1:108786317, a snv, in the first example below) has no RNA seq reads at all (and is not included in the bam-readcount RNA seq output), pvacseq will terminate as shown below. 

Data: [Archive-1.zip](https://github.com/griffithlab/pVAC-Seq/files/511983/Archive-1.zip)

Ps. i got the location above from the error message below. 
Ps2. I was able to run the whole pipeline as in the above dataset using only 1 variant in the vcf file that I know has RNA seq reads.

```
$ pvacseq run -e 8 -i additional_input_file_list.yaml -b 500 4A_missense_frameshift.vcf.anno 4A HLA-A*24:02 NetMHC pvacseq_output_2 -k -s 2
Executing MHC Class I predictions
Converting VCF to TSV
Traceback (most recent call last):
  File "/Users/nir2023/anaconda/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/Users/nir2023/anaconda/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 77, in main
    args[0].func.main(args[1])
  File "/Users/nir2023/anaconda/lib/python3.5/site-packages/pvacseq/lib/main.py", line 252, in main
    pipeline.execute()
  File "/Users/nir2023/anaconda/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 222, in execute
    self.convert_vcf()
  File "/Users/nir2023/anaconda/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 78, in convert_vcf
    lib.convert_vcf.main(convert_params)
  File "/Users/nir2023/anaconda/lib/python3.5/site-packages/pvacseq/lib/convert_vcf.py", line 215, in main
    if ref_base in coverage[variant_type][coverage_type][chromosome][str(bam_readcount_position)]:
KeyError: '108786317'
```

I tried running it without the bam-readcount RNA snv info in the yaml file, (since it was a snv that was returned in the error above). I got a similar error (see below), and that specific location also has no RNA seq reads (chr12:234963 in VCF, deletion GC to G).

[Archive-2.zip](https://github.com/griffithlab/pVAC-Seq/files/512033/Archive-2.zip)

```
$ pvacseq run -e 8 -i additional_input_file_list.yaml -b 500 4A_missense_frameshift.vcf.anno 4A HLA-A*24:02 NetMHC test -k -s 2
Executing MHC Class I predictions
Converting VCF to TSV
Traceback (most recent call last):
  File "/Users/nir2023/anaconda/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/Users/nir2023/anaconda/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 77, in main
    args[0].func.main(args[1])
  File "/Users/nir2023/anaconda/lib/python3.5/site-packages/pvacseq/lib/main.py", line 252, in main
    pipeline.execute()
  File "/Users/nir2023/anaconda/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 222, in execute
    self.convert_vcf()
  File "/Users/nir2023/anaconda/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 78, in convert_vcf
    lib.convert_vcf.main(convert_params)
  File "/Users/nir2023/anaconda/lib/python3.5/site-packages/pvacseq/lib/convert_vcf.py", line 215, in main
    if ref_base in coverage[variant_type][coverage_type][chromosome][str(bam_readcount_position)]:
KeyError: '234964'
```

**Comment by susannasiebert** [comment]
The hotfix release v4.0.1 is now live.

**Comment by strixeh** [comment]
Great, thanks!
