### ISSUE TITLE
4.0.2: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by serge2016** [griffithlab/pVAC-Seq#225]
Hello! Thanks for the update!
But there is a bug, as I think:
pvacseq works only of PEPTIDE_SEQUENCE_LENGTH is strictly more than 2*EPITOPE_LENGTH (if we specify PEPTIDE_SEQUENCE_LENGTH). Otherwise it fails:
```
$ pvacseq run -e 9 -l 18 pat27.annot-vep.tumorOnly.vcf pat27_4 "HLA-A*02:01,HLA-A*11:01" NetMHC ./
Executing MHC Class I predictions
Converting VCF to TSV
TSV file already exists. Skipping.
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-48
Split TSV file for Entries 1-48 already exists. Skipping.
Completed
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Entries 1-96
Completed
Processing entries for Allele HLA-A*02:01 and Epitope Length 9 - Entries 1-96
IEDB file for Allele HLA-A*02:01 and Epitope Length 9 with Method NetMHC (Entries 1-96) already exists. Skipping.
Parsing IEDB Output for Allele HLA-A*02:01 and Epitope Length 9 - Entries 1-96
Traceback (most recent call last):
  File "/soft/pvacseq/bin/pvacseq", line 9, in <module>
    load_entry_point('pvacseq==4.0.2', 'console_scripts', 'pvacseq')()
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/pvacseq.py", line 77, in main
    args[0].func.main(args[1])
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/main.py", line 282, in main
    pipeline.execute()
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/pipeline.py", line 251, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/pipeline.py", line 389, in call_iedb_and_parse_outputs
    lib.parse_output.main(params)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 433, in main
    iedb_results = process_input_iedb_file(args.input_iedb_files, tsv_entries, args.key_file, args.top_result_per_mutation, args.top_score_metric)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 344, in process_input_iedb_file
    iedb_results              = parse_iedb_file(input_iedb_files, tsv_entries, key_file)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 250, in parse_iedb_file
    return match_wildtype_and_mutant_entries(iedb_results, wt_iedb_results)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 198, in match_wildtype_and_mutant_entries
    match_wildtype_and_mutant_entry_for_inframe_indel(result, mt_position, wt_results, previous_result, iedb_results_for_wt_iedb_result_key)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 129, in match_wildtype_and_mutant_entry_for_inframe_indel
    if previous_result['match_direction'] == 'left':
TypeError: 'NoneType' object is not subscriptable
```
[pat27.annot-vep.tumorOnly.zip.txt](https://github.com/griffithlab/pVAC-Seq/files/586620/pat27.annot-vep.tumorOnly.zip.txt)

**Comment by susannasiebert** [comment]
Hi Serge,
Thanks for pointing out this error. This is corner case that I failed to test for. I will work on a hotfix release.
Thanks,
Susanna

**Comment by susannasiebert** [comment]
@serge2016 Could you please attach to this issue the vcf file that is causing this error? I am not able to reproduce this error with our test data so I think that your specific case of inframe indel is also playing a role here. I'm suspecting that it might be a very long deletion.

**Comment by serge2016** [comment]
@susannasiebert Dear Susanna, the input file already was attached to the message. You have to remove ".txt" from the filename and unzip it and you'll get the input VCF.

**Comment by Akado2009** [comment]
+1. Got the same error today. It has something to do with previous_results dictionary, cuz you are trying to modify keys that are missing from the dicitonary itself. Thanks in advance!

**Comment by serge2016** [comment]
Here is one more traceback for the v4.0.2:
'''
$ pvacseq run -e 8 -l 17 pat126.annot-vep.tumorOnly.vcf pat126 "HLA-A*01:01,HLA-A*02:01,HLA-B*08:01,HLA-B*40:01,HLA-C*07:01" NetMHC ./
'''
'''
...
Processing entries for Allele HLA-A*01:01 and Epitope Length 8 - Entries 801-1000
Running IEDB on Allele HLA-A*01:01 and Epitope Length 8 with Method NetMHC - Entries 801-1000
Completed
Parsing IEDB Output for Allele HLA-A*01:01 and Epitope Length 8 - Entries 801-1000
Traceback (most recent call last):
  File "/soft/pvacseq/bin/pvacseq", line 9, in <module>
    load_entry_point('pvacseq==4.0.2', 'console_scripts', 'pvacseq')()
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/pvacseq.py", line 77, in main
    args[0].func.main(args[1])
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/main.py", line 282, in main
    pipeline.execute()
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/pipeline.py", line 251, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/pipeline.py", line 389, in call_iedb_and_parse_outputs
    lib.parse_output.main(params)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 433, in main
    iedb_results = process_input_iedb_file(args.input_iedb_files, tsv_entries, args.key_file, args.top_result_per_mutation, args.top_score_metric)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 344, in process_input_iedb_file
    iedb_results              = parse_iedb_file(input_iedb_files, tsv_entries, key_file)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 250, in parse_iedb_file
    return match_wildtype_and_mutant_entries(iedb_results, wt_iedb_results)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 198, in match_wildtype_and_mutant_entries
    match_wildtype_and_mutant_entry_for_inframe_indel(result, mt_position, wt_results, previous_result, iedb_results_for_wt_iedb_result_key)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 139, in match_wildtype_and_mutant_entry_for_inframe_indel
    alternate_best_match_wt_result      = wt_results[str(alternate_best_match_position)]
KeyError: '0'
'''
I didn't check your last commit yet((
The input file already is attached to the message. You have to remove ".txt" from the filename and unzip it and you'll get the new input VCF.
[pat126.annot-vep.tumorOnly.zip.txt](https://github.com/griffithlab/pVAC-Seq/files/590282/pat126.annot-vep.tumorOnly.zip.txt)

**Comment by susannasiebert** [comment]
@serge2016 Thanks for the second test case. I'll make sure my fix works on this data as well.

**Comment by serge2016** [comment]
@susannasiebert Thank you! I hope to see the new release very soon!

**Comment by susannasiebert** [comment]
@serge2016 I'm planning on making a new release this week.

**Comment by serge2016** [comment]
`pvacseq run -e 8 -l 17 pat38.annot-vep.tumorOnly.vcf pat38 "HLA-A*02:01,HLA-A*03:01,HLA-B*15:17,HLA-B*40:02,HLA-C*07:01" NetMHC ./`
```
Processing entries for Allele HLA-A*02:01 and Epitope Length 8 - Entries 2001-2200
Running IEDB on Allele HLA-A*02:01 and Epitope Length 8 with Method NetMHC - Entries 2001-2200
Completed
Parsing IEDB Output for Allele HLA-A*02:01 and Epitope Length 8 - Entries 2001-2200
Traceback (most recent call last):
  File "/soft/pvacseq/bin/pvacseq", line 9, in <module>
    load_entry_point('pvacseq==4.0.2', 'console_scripts', 'pvacseq')()
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/pvacseq.py", line 77, in main
    args[0].func.main(args[1])
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/main.py", line 282, in main
    pipeline.execute()
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/pipeline.py", line 251, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/pipeline.py", line 389, in call_iedb_and_parse_outputs
    lib.parse_output.main(params)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 433, in main
    iedb_results = process_input_iedb_file(args.input_iedb_files, tsv_entries, args.key_file, args.top_result_per_mutation, args.top_score_metric)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 344, in process_input_iedb_file
    iedb_results              = parse_iedb_file(input_iedb_files, tsv_entries, key_file)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 250, in parse_iedb_file
    return match_wildtype_and_mutant_entries(iedb_results, wt_iedb_results)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 198, in match_wildtype_and_mutant_entries
    match_wildtype_and_mutant_entry_for_inframe_indel(result, mt_position, wt_results, previous_result, iedb_results_for_wt_iedb_result_key)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 139, in match_wildtype_and_mutant_entry_for_inframe_indel
    alternate_best_match_wt_result      = wt_results[str(alternate_best_match_position)]
KeyError: '0'
```
The input file already is attached to the message. You have to remove ".txt" from the filename and unzip it and you'll get the new input VCF.
[pat38.annot-vep.tumorOnly.zip.txt](https://github.com/griffithlab/pVAC-Seq/files/591362/pat38.annot-vep.tumorOnly.zip.txt)

**Comment by serge2016** [comment]
I have tested your fix for pat_27. It Works!

**Comment by serge2016** [comment]
`$ pvacseq run -e 8 -l 17 pat45.annot-vep.tumorOnly.vcf pat45 "HLA-A*02:01,HLA-A*24:02,HLA-B*44:02,HLA-B*51:01,HLA-C*05:01,HLA-C*15:02" NetMHC ./`
```
Processing entries for Allele HLA-A*02:01 and Epitope Length 8 - Entries 5001-5000
Running IEDB on Allele HLA-A*02:01 and Epitope Length 8 with Method NetMHC - Entries 5001-5000
Completed
Parsing IEDB Output for Allele HLA-A*02:01 and Epitope Length 8 - Entries 5001-5000
Traceback (most recent call last):
  File "/soft/pvacseq/bin/pvacseq", line 9, in <module>
    load_entry_point('pvacseq==4.0.2', 'console_scripts', 'pvacseq')()
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/pvacseq.py", line 77, in main
    args[0].func.main(args[1])
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/main.py", line 282, in main
    pipeline.execute()
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/pipeline.py", line 251, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/pipeline.py", line 389, in call_iedb_and_parse_outputs
    lib.parse_output.main(params)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 433, in main
    iedb_results = process_input_iedb_file(args.input_iedb_files, tsv_entries, args.key_file, args.top_result_per_mutation, args.top_score_metric)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 344, in process_input_iedb_file
    iedb_results              = parse_iedb_file(input_iedb_files, tsv_entries, key_file)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 210, in parse_iedb_file
    protein_label  = int(line['seq_num'])
KeyError: 'seq_num'
```
The input file already is attached to the message. You have to remove ".txt" from the filename and unzip it and you'll get the new input VCF.
[pat45.annot-vep.tumorOnly.zip.txt](https://github.com/griffithlab/pVAC-Seq/files/591460/pat45.annot-vep.tumorOnly.zip.txt)

**Comment by susannasiebert** [comment]
I made a new issue (#227) for the latest error since it doesn't seem to be directly related to the parsing of indels.

**Comment by susannasiebert** [comment]
The newest release (4.0.3) should fix these errors.

**Comment by serge2016** [comment]
I agree. Fixed.
