### ISSUE TITLE
KeyError: 'seq_num'

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVAC-Seq#227]
```
$ pvacseq run -e 8 -l 17 pat45.annot-vep.tumorOnly.vcf pat45 "HLA-A*02:01,HLA-A*24:02,HLA-B*44:02,HLA-B*51:01,HLA-C*05:01,HLA-C*15:02" NetMHC ./
```
```
...
Processing entries for Allele HLA-A*02:01 and Epitope Length 8 - Entries 5001-5000
Running IEDB on Allele HLA-A*02:01 and Epitope Length 8 with Method NetMHC - Entries 5001-5000
Completed
Parsing IEDB Output for Allele HLA-A*02:01 and Epitope Length 8 - Entries 5001-5000
Traceback (most recent call last):
  File "/soft/pvacseq/bin/pvacseq", line 9, in <module>
    load_entry_point('pvacseq==4.0.2', 'console_scripts', 'pvacseq')()
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/pvacseq.py", line 77, in main
    args[0].func.main(args[1])
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/main.py", line 282, in main
    pipeline.execute()
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/pipeline.py", line 251, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/pipeline.py", line 389, in call_iedb_and_parse_outputs
    lib.parse_output.main(params)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 433, in main
    iedb_results = process_input_iedb_file(args.input_iedb_files, tsv_entries, args.key_file, args.top_result_per_mutation, args.top_score_metric)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 344, in process_input_iedb_file
    iedb_results              = parse_iedb_file(input_iedb_files, tsv_entries, key_file)
  File "/soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.2-py3.5.egg/pvacseq/lib/parse_output.py", line 210, in parse_iedb_file
    protein_label  = int(line['seq_num'])
KeyError: 'seq_num'
```
The input file already is attached to the message. You have to remove ".txt" from the filename and unzip it and you'll get the new input VCF.
[pat45.annot-vep.tumorOnly.zip.txt](https://github.com/griffithlab/pVAC-Seq/files/592130/pat45.annot-vep.tumorOnly.zip.txt)

**Comment by susannasiebert** [comment]
The newest release (4.0.3) should fix this error.

**Comment by serge2016** [comment]
Agree. Fixed.
