### ISSUE TITLE
Using local copy of IEDB.

### ISSUE THREAD

**Issue by Akado2009** [griffithlab/pVAC-Seq#231]
Hello! As it was suggested earlier in 4.0.2 release review, I can now use local copy of IEDB. I downloaded it from [http://tools.iedb.org/mhci/download/](IEDB). And now, when I'm trying to execute pvacseq with --iedb-install-directory parameter, I get errors.

` pvacseq run -e 8 --iedb-install-directory /home/akado2009/Desktop/IEDB input.vcf Test H-2-Db,H-2-Dd,H-2-Kb,H-2-Kd,H-2-Kk,H-2-Ld NetMHC .` where ` /home/akado2009/Desktop/IEDB` is a directory containing mhc-i folder. I get these errors:
` Executing MHC Class I predictions
Converting VCF to TSV
TSV file already exists. Skipping.
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-64
Split TSV file for Entries 1-64 already exists. Skipping.
Completed
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Entries 1-128
Completed
Processing entries for Allele H-2-Db and Epitope Length 8 - Entries 1-128
Running IEDB on Allele H-2-Db and Epitope Length 8 with Method NetMHC - Entries 1-128
Traceback (most recent call last):
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 334, in <module>
    Prediction().main()
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 326, in main
    elif (len(args)  == 4):                            self.commandline_input(args)  # args=[method, mhc, length, fname]
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 67, in commandline_input
    mhc_scores = mhc_predictor.predict(input.input_protein.sequences)
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/seqpredictor.py", line 1010, in predict
    scores.append(predictor.predict_sequence(sequence,pred))
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/seqpredictor.py", line 251, in predict_sequence
    scores = netmhc_prediction(allele_name, str(self.length), sequence)
  File "/home/akado2009/Desktop/IEDB/mhc_i/method/netmhc_4_0_executable/__init__.py", line 33, in predict
    process = Popen(cmd, stdout=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Completed
Parsing IEDB Output for Allele H-2-Db and Epitope Length 8 - Entries 1-128
Completed
Processing entries for Allele H-2-Dd and Epitope Length 8 - Entries 1-128
Running IEDB on Allele H-2-Dd and Epitope Length 8 with Method NetMHC - Entries 1-128
Traceback (most recent call last):
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 334, in <module>
    Prediction().main()
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 326, in main
    elif (len(args)  == 4):                            self.commandline_input(args)  # args=[method, mhc, length, fname]
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 67, in commandline_input
    mhc_scores = mhc_predictor.predict(input.input_protein.sequences)
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/seqpredictor.py", line 1010, in predict
    scores.append(predictor.predict_sequence(sequence,pred))
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/seqpredictor.py", line 251, in predict_sequence
    scores = netmhc_prediction(allele_name, str(self.length), sequence)
  File "/home/akado2009/Desktop/IEDB/mhc_i/method/netmhc_4_0_executable/__init__.py", line 33, in predict
    process = Popen(cmd, stdout=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Completed
Parsing IEDB Output for Allele H-2-Dd and Epitope Length 8 - Entries 1-128
Completed
Processing entries for Allele H-2-Kb and Epitope Length 8 - Entries 1-128
Running IEDB on Allele H-2-Kb and Epitope Length 8 with Method NetMHC - Entries 1-128
Traceback (most recent call last):
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 334, in <module>
    Prediction().main()
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 326, in main
    elif (len(args)  == 4):                            self.commandline_input(args)  # args=[method, mhc, length, fname]
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 67, in commandline_input
    mhc_scores = mhc_predictor.predict(input.input_protein.sequences)
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/seqpredictor.py", line 1010, in predict
    scores.append(predictor.predict_sequence(sequence,pred))
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/seqpredictor.py", line 251, in predict_sequence
    scores = netmhc_prediction(allele_name, str(self.length), sequence)
  File "/home/akado2009/Desktop/IEDB/mhc_i/method/netmhc_4_0_executable/__init__.py", line 33, in predict
    process = Popen(cmd, stdout=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Completed
Parsing IEDB Output for Allele H-2-Kb and Epitope Length 8 - Entries 1-128
Completed
Processing entries for Allele H-2-Kd and Epitope Length 8 - Entries 1-128
Running IEDB on Allele H-2-Kd and Epitope Length 8 with Method NetMHC - Entries 1-128
Traceback (most recent call last):
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 334, in <module>
    Prediction().main()
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 326, in main
    elif (len(args)  == 4):                            self.commandline_input(args)  # args=[method, mhc, length, fname]
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 67, in commandline_input
    mhc_scores = mhc_predictor.predict(input.input_protein.sequences)
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/seqpredictor.py", line 1010, in predict
    scores.append(predictor.predict_sequence(sequence,pred))
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/seqpredictor.py", line 251, in predict_sequence
    scores = netmhc_prediction(allele_name, str(self.length), sequence)
  File "/home/akado2009/Desktop/IEDB/mhc_i/method/netmhc_4_0_executable/__init__.py", line 33, in predict
    process = Popen(cmd, stdout=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Completed
Parsing IEDB Output for Allele H-2-Kd and Epitope Length 8 - Entries 1-128
Completed
Processing entries for Allele H-2-Kk and Epitope Length 8 - Entries 1-128
Running IEDB on Allele H-2-Kk and Epitope Length 8 with Method NetMHC - Entries 1-128
Traceback (most recent call last):
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 334, in <module>
    Prediction().main()
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 326, in main
    elif (len(args)  == 4):                            self.commandline_input(args)  # args=[method, mhc, length, fname]
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 67, in commandline_input
    mhc_scores = mhc_predictor.predict(input.input_protein.sequences)
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/seqpredictor.py", line 1010, in predict
    scores.append(predictor.predict_sequence(sequence,pred))
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/seqpredictor.py", line 251, in predict_sequence
    scores = netmhc_prediction(allele_name, str(self.length), sequence)
  File "/home/akado2009/Desktop/IEDB/mhc_i/method/netmhc_4_0_executable/__init__.py", line 33, in predict
    process = Popen(cmd, stdout=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Completed
Parsing IEDB Output for Allele H-2-Kk and Epitope Length 8 - Entries 1-128
Completed
Processing entries for Allele H-2-Ld and Epitope Length 8 - Entries 1-128
Running IEDB on Allele H-2-Ld and Epitope Length 8 with Method NetMHC - Entries 1-128
Traceback (most recent call last):
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 334, in <module>
    Prediction().main()
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 326, in main
    elif (len(args)  == 4):                            self.commandline_input(args)  # args=[method, mhc, length, fname]
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/predict_binding.py", line 67, in commandline_input
    mhc_scores = mhc_predictor.predict(input.input_protein.sequences)
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/seqpredictor.py", line 1010, in predict
    scores.append(predictor.predict_sequence(sequence,pred))
  File "/home/akado2009/Desktop/IEDB/mhc_i/src/seqpredictor.py", line 251, in predict_sequence
    scores = netmhc_prediction(allele_name, str(self.length), sequence)
  File "/home/akado2009/Desktop/IEDB/mhc_i/method/netmhc_4_0_executable/__init__.py", line 33, in predict
    process = Popen(cmd, stdout=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Completed
Parsing IEDB Output for Allele H-2-Ld and Epitope Length 8 - Entries 1-128
Completed
Combining Parsed IEDB Output Files
Completed
Running Binding Filters
Completed

Done: pvacseq has completed. File /home/akado2009/Desktop/pvacIedb/pvacseq-bss/tests/input_data/MHC_Class_I/Test.final.tsv contains list of filtered putative neoantigensWe recommend appending coverage information and running `pvacseq coverage_filter` to filter based on sequencing coverage information
`
Apparently, output files are empty. 
So, if you know, what can I do? Or there is a problem with IEDB itself?

King regards, akado2009.
[input.vcf.gz](https://github.com/griffithlab/pVAC-Seq/files/594862/input.vcf.gz)

**Comment by susannasiebert** [comment]
This seems to be a problem with your python environments. What are you using for emulating your python environment? Are you using Conda? Do you have the following folder `/usr/lib/python2.7`?

**Comment by Akado2009** [comment]
Yup, I have `/usr/lib/python2.7`. I have tow separate versions of python (2.7 & 3.5) with separate PYTHONPATH.

**Comment by susannasiebert** [comment]
Do you have `/usr/lib/python2.7/subprocess.py`?

**Comment by Akado2009** [comment]
Yup, I have it as well.

**Comment by susannasiebert** [comment]
Can you set a breakpoint before `process = Popen(cmd, stdout=PIPE)` and evaluate `cmd`?

```
import pdb
pdb.set_trace()
process = Popen(cmd, stdout=PIPE)
```

**Comment by Akado2009** [comment]
There is no result from this operation, I do not enter a debugger mode. It's kinda weired, since I can't even print cmd itself.

**Comment by susannasiebert** [comment]
Hm, I'm sorry but I'm not really sure what could be the issue. We only tried using IEDB locally under Conda, since that is our recommended installation method. Maybe you could try using Conda for your python environment management and see if that fixes things.

You might also want to try contacting IEDB and see if they can help you with this error.

**Comment by Akado2009** [comment]
Anyway thanks, except this little issue, you soft is working pretty neat!

**Comment by susannasiebert** [comment]
You're welcome. Sorry I couldn't be of more help. Is it ok if I close this issue?

**Comment by Akado2009** [comment]
Yup, it is ok!

**Comment by cedarice** [comment]
I have got the same problem using pvac-seq v4.0.3, the reason is lacking tsch program. So install tcsh will fix this problem.
@Akado2009 @susannasiebert

**Comment by Akado2009** [comment]
@cedarice, thanks, you are amazing!
I confirm, that it helped me to fix this problem!
`sudo apt get install tcsh`

**Comment by susannasiebert** [comment]
@cedarice Thank you for your help in finding a solution to fixing this error. I will make a note in the installation instructions about it.

**Comment by cedarice** [comment]
Additionally, pvacseq appears it is not compatible to using nohup. When using nohup, it will return "IOError: [Errno 9] Bad file descriptor" error messages.

**Comment by juheon** [comment]
In case, you don't have root access and cannot install tcsh using 'sudo'. You need to replace the shebang in following files to your local tcsh address.

By default, following files have the shebang
#! /bin/tcsh -f

You need to replace the shebang with your local tcsh address.
#! <your tcsh directory>/tcsh -f

mhc_i/method/netmhc-4.0-executable/netmhc_4_0_executable/netMHC
mhc_i/method/netmhccons-1.1-executable/netmhccons_1_1_executable/netMHCcons
mhc_i/method/netmhcpan-2.8-executable/netmhcpan_2_8_executable/netMHCpan
mhc_i/method/netmhcpan-3.0-executable/netmhcpan_3_0_executable/netMHCpan
mhc_i/method/netmhcstabpan-1.0-executable/netmhcstabpan_1_0_executable/netMHCstabpan
mhc_i/method/pickpocket-1.1-executable/pickpocket_1_1_executable/PickPocket
