### ISSUE TITLE
ConnectionError: HTTPConnectionPool(host='www.cbs.dtu.dk'

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVAC-Seq#239]
Hey Guys,

Facing this error at NetChop prediction, 

ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.cbs.dtu.dk', port=80): Max retries exceeded with url: /cgi-bin/webface2.fcgi (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f6df9c33fd0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by susannasiebert** [comment]
Looks like maybe the NetChop server is down. Do you still get this error today?

**Comment by venkataddala** [comment]
I'm trying to run again, got faced with new error, 

Traceback (most recent call last):
  File "/software/python/Python-3.5.0/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/main.py", line 282, in main
    pipeline.execute()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 253, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 391, in call_iedb_and_parse_outputs
    lib.parse_output.main(params)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 452, in main
    iedb_results = process_input_iedb_file(args.input_iedb_files, tsv_entries, args.key_file, args.top_result_per_mutation, args.top_score_metric)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 363, in process_input_iedb_file
    iedb_results              = parse_iedb_file(input_iedb_files, tsv_entries, key_file)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 269, in parse_iedb_file
    return match_wildtype_and_mutant_entries(iedb_results, wt_iedb_results)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 214, in match_wildtype_and_mutant_entries
    match_wildtype_and_mutant_entry_for_frameshift(result, mt_position, wt_results, previous_result)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 95, in match_wildtype_and_mutant_entry_for_frameshift
    if mutation_position == 1 and int(previous_result['mutation_position']) <= 1:
TypeError: 'NoneType' object is not subscriptable

**Comment by susannasiebert** [comment]
Which version of pVAC-Seq are you running? We made a new release last week (4.0.4) that fixes a similar error.

**Comment by venkataddala** [comment]
Thank you, I will make an update.

--
Regards
Venkat Addala  <http://in.linkedin.com/in/venkataddala/>
Computational Biologist

**Comment by venkataddala** [comment]
Another error.. in 4.0.4 

Traceback (most recent call last):
  File "/software/python/Python-3.5.0/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/main.py", line 282, in main
    pipeline.execute()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 253, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 391, in call_iedb_and_parse_outputs
    lib.parse_output.main(params)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 452, in main
    iedb_results = process_input_iedb_file(args.input_iedb_files, tsv_entries, args.key_file, args.top_result_per_mutation, args.top_score_metric)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 363, in process_input_iedb_file
    iedb_results              = parse_iedb_file(input_iedb_files, tsv_entries, key_file)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 269, in parse_iedb_file
    return match_wildtype_and_mutant_entries(iedb_results, wt_iedb_results)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 214, in match_wildtype_and_mutant_entries
    match_wildtype_and_mutant_entry_for_frameshift(result, mt_position, wt_results, previous_result)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 67, in match_wildtype_and_mutant_entry_for_frameshift
    if previous_result['mutation_position'] > 0:
TypeError: unorderable types: str() > int()

**Comment by susannasiebert** [comment]
@venkataddala Can you please attach the VCF that is causing this error. I haven't seen this error before and it will help me pinpoint the edge case that is causing it.

**Comment by venkataddala** [comment]
Sure, I will do that, But I used same VCF in older version before 4.0.3, It
got failed due to NetChop server down, but i got result without using
NetChop.

--
Regards
Venkat Addala  <http://in.linkedin.com/in/venkataddala/>
Computational Biologist

**Comment by susannasiebert** [comment]
We made some changes to the parser in one of the recent versions that seems to have introduced some bugs for edge cases that aren't covered by our test suite. As such your VCF might've succeeded before but could fail now. I won't be able to tell until I see the VCF and am able to determine which variant is causing this error. It would also be helpful if you could post the exact command that you ran.

**Comment by susannasiebert** [comment]
If you prefer to not attach the vcf to this issue you can also email it to pvacseq-support@genome.wustl.edu

**Comment by venkataddala** [comment]
I don't have permissions to get VCF file form cluster or email them. Here is the command used,

pvacseq run --iedb-install-directory /software/IEDB_MHC/IEDB_MHC-2.15.1 /mnt/lustre/working/genomeinfo/share/temp/venkatA/HLA_Typing/pVAC-Seq/VEP/f75cc1d9-1fc2-4403-b7c5-b677a0097b2.vcf MELA_7885_qsnp - --net-chop-method cterm -e 9 HLA-A*01:01 NetMHC NetMHCpan /working/genomeinfo/share/temp/venkatA/HLA_Typing/pVAC-Seq/pVACoutput/

**Comment by venkataddala** [comment]
pvacseq run --iedb-install-directory /software/IEDB_MHC/IEDB_MHC-2.15.1 -e 9 --netmhc-stab /mnt/lustre/working/genomeinfo/share/temp/venkatA/HLA_Typing/pVAC-Seq/VEP/err3.vcf MELA_7885_gatk HLA-A*01:01 NetMHC NetMHCIIpan /working/genomeinfo/share/temp/venkatA/HLA_Typing/pVAC-Seq/pVACoutput

I got this error when i ran above command,

Parsing IEDB Output for Allele HLA-A*01:01 and Epitope Length 9 - Entries 5201-5400
Traceback (most recent call last):
  File "/software/python/Python-3.5.0/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/main.py", line 282, in main
    pipeline.execute()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 253, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 391, in call_iedb_and_parse_outputs
    lib.parse_output.main(params)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 452, in main
    iedb_results = process_input_iedb_file(args.input_iedb_files, tsv_entries, args.key_file, args.top_result_per_mutation, args.top_score_metric)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 363, in process_input_iedb_file
    iedb_results              = parse_iedb_file(input_iedb_files, tsv_entries, key_file)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 269, in parse_iedb_file
    return match_wildtype_and_mutant_entries(iedb_results, wt_iedb_results)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 214, in match_wildtype_and_mutant_entries
    match_wildtype_and_mutant_entry_for_frameshift(result, mt_position, wt_results, previous_result)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 67, in match_wildtype_and_mutant_entry_for_frameshift
    if previous_result['mutation_position'] > 0:
TypeError: unorderable types: str() > int()

**Comment by susannasiebert** [comment]
I understand that you are not able to share your input VCF with us. Unfortunately, without having the input data I am not able to reproduce this error and am not able to figure out what exactly is causing this error. Would you be able to share a subset of the data with us? For example, could you share the chunk of data that contains the variant causing this error (/working/genomeinfo/share/temp/venkatA/HLA_Typing/pVAC-Seq/pVACoutput/MELA_7885_gatk.tsv_2601-2700) or would you be allowed to share the variant that is causing this error?

If you are not allowed to share any real patient data I would need to ask you to come up with fake input data that is also producing this error so that I can reproduce this error on my end.

**Comment by susannasiebert** [comment]
I made a new release that contains some code changes to try and address your error. Without test data I'm not able to say for sure that it will fix the error you're experiencing but please update to the latest version (4.0.5) and see if that solves this issue.
