### ISSUE TITLE
KeyError: 'netmhcpan'

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVAC-Seq#260]
Command Used
pvacseq run --iedb-install-directory IEDB_MHC-2.15.1 -b 500 -c 1 -e 8,9,10,11 MEL_20054_Ex_2.vcf MEL_IED_Alo HLA-A*01:01,HLA-A*11:01,HLA-B*08:01,HLA-B*18:01,HLA-C*07:01,HLA-C*07:01 NetMHC NetMHCpan SMMalign SMMPMBEC /working/genomeinfo/share/temp/venkatA/Analysis/HLA_Typing/pVAC-Seq/pVACoutput

Error
Running IEDB on Allele HLA-A*01:01 and Epitope Length 9 with Method NetMHC - Entries 2601-2800
Completed
Running IEDB on Allele HLA-A*01:01 and Epitope Length 9 with Method NetMHCpan - Entries 2601-2800
Completed
Running IEDB on Allele HLA-A*01:01 and Epitope Length 9 with Method SMMPMBEC - Entries 2601-2800
Completed
Parsing IEDB Output for Allele HLA-A*01:01 and Epitope Length 9 - Entries 2601-2800
Traceback (most recent call last):
  File "IEDB_MHC-2.15.1/mhc_i/src/predict_binding.py", line 334, in <module>
    Prediction().main()
  File "IEDB_MHC-2.15.1/mhc_i/src/predict_binding.py", line 326, in main
    elif (len(args)  == 4):  self.commandline_input(args)  # args=[method, mhc, length, fname]
  File "IEDB_MHC-2.15.1/mhc_i/src/predict_binding.py", line 68, in commandline_input
    table_rows = self.format_binding(input, mhc_scores, method, use_cutoff, cutoff_value)
  File "IEDB_MHC-2.15.1/mhc_i/src/predict_binding.py", line 116, in format_binding
    self.add_rows_binding(allele, length, proteins, score, method_list, cutoff, value)
  File "IEDB_MHC-2.15.1/mhc_i/src/predict_binding.py", line 122, in add_rows_binding
    for (k, prediction) in enumerate(predictions):
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/software/python/Python-3.5.0/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/main.py", line 282, in main
    pipeline.execute()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 253, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 391, in call_iedb_and_parse_outputs
    lib.parse_output.main(params)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 509, in main
    row["%s WT Score" % pretty_method] = wt_scores[method]
KeyError: 'netmhcpan'

Is the length of  aa variant is not matching with netmhcpan ? in this

**Comment by susannasiebert** [comment]
Could be. I will need to do some more testing to figure out exactly what is going on.

**Comment by susannasiebert** [comment]
A fix for this bug is in PR #262 and will be part of the next release.

**Comment by susannasiebert** [comment]
The newest release (4.0.7) fixes this issue. Please upgrade your install of pVAC-Seq and let me know if it works for you.
