### ISSUE TITLE
Not able to connect NetChop server 

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVAC-Seq#263]
I'm using pVAC 4.0.6 and not able to connect NetChop server, 

Command Used
pvacseq run --iedb-install-directory /software/IEDB_MHC/IEDB_MHC-20170201 -b 500 -c 1 -e 8,9,10,11 --net-chop-method cterm --netmhc-stab  /mnt/lustre/working/genomeinfo/share/temp/venkatA/Analysis/Neoantigens/pVAC_Input/SO-0115_SOM_HC_VEP_Filtered.vcf SO-0115 HLA-A*01:01,HLA-A*03:01,HLA-B*07:02,HLA-B*08:01,HLA-C*07:02,HLA-C*07:01 NetMHC NetMHCpan SMMalign SMMPMBEC /working/genomeinfo/share/temp/venkatA/Analysis/Neoantigens/pVAC_Output

VCF file
[SO_0115.vcf.zip](https://github.com/griffithlab/pVAC-Seq/files/760188/SO_0115.vcf.zip)

Error
Waiting for results from NetChop...
Traceback (most recent call last):
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/software/python/Python-3.5.0/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/software/python/Python-3.5.0/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/software/python/Python-3.5.0/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/software/python/Python-3.5.0/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/software/python/Python-3.5.0/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7ff1c2d73d30>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.cbs.dtu.dk', port=80): Max retries exceeded with url: /cgi-bin/webface2.fcgi (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff1c2d73d30>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/python/Python-3.5.0/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/main.py", line 285, in main
    pipeline.execute()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 277, in execute
    self.net_chop()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 226, in net_chop
    str(self.net_chop_threshold)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/net_chop.py", line 82, in main
    'thresh':'%0f'%args.threshold
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.cbs.dtu.dk', port=80): Max retries exceeded with url: /cgi-bin/webface2.fcgi (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff1c2d73d30>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by susannasiebert** [comment]
Well, you're getting a connection timed out error - "Failed to establish a new connection". When I go to the NetChop analysis webpage and try to use it I get the following message: "Service disabled. Due to technical difficulties, this service has been disabled for online analysis. For some services, you can contact the authors for a copy of the analysis software." I'm not sure if this is temporary or permanent but it looks like for now you won't be able to use the NetChop feature in pVAC-Seq.

**Comment by venkataddala** [comment]
NetChop server is working now and I got some output with error below but not able to generate "final.tsv" file.

Waiting for results from NetChop... -Traceback (most recent call last):
  File "/software/python/Python-3.5.0/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/main.py", line 285, in main
    pipeline.execute()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 277, in execute
    self.net_chop()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 226, in net_chop
    str(self.net_chop_threshold)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/net_chop.py", line 115, in main
    max_cleavage_score = max(cleavage_scores.items(), key=lambda x: x[1])
ValueError: max() arg is an empty sequence

**Comment by susannasiebert** [comment]
A fix for this issue is in PR #266 and will be part of the next release.

**Comment by susannasiebert** [comment]
The newest release (4.0.7) fixes the NetChopissue. Please upgrade your install of pVAC-Seq and let me know if you are able to run your data successfully.
