### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '16&16'

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVAC-Seq#267]
Hi guys, 

I have a problem when I'm running this vcf, However i found such error resolved in previous version, can you check with this vcf file. Please help.

pvacseq run --iedb-install-directory /software/IEDB_MHC/IEDB_MHC-20170201 -b 500 -e 8,9,10,11 -r=50 --net-chop-method cterm --netmhc-stab --fasta-size=600 --keep-tmp-files /working/genomeinfo/share/temp/venkatA/Analysis/Neoantigens/VCF_SHC/after_treatment_exome/temp_vcf/MESO-11202-AT_WES_VEP_filterd.vcf MESO-11202-WES_AT HLA-A*01:24,HLA-B*08:01,HLA-B*55:01,HLA-C*03:07,HLA-A*01:01,HLA-A*24:129,HLA-A*24:02,HLA-B*58:01,HLA-B*55:28,HLA-B*55:27,HLA-C*07:01,HLA-C*03:03,DRB1*03:01,DRB1*13:02 NNalign NetMHC NetMHCpan NetMHCIIpan SMM PickPocket SMMalign SMMPMBEC  /working/genomeinfo/share/temp/venkatA/Analysis/Neoantigens/pVAC_Output/MESO-11202-WES_AT

Error

Executing MHC Class I predictions
Converting VCF to TSV
Traceback (most recent call last):
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/vcf/parser.py", line 481, in _parse_samples
    sampdat[i] = int(vals)
ValueError: invalid literal for int() with base 10: '16&16'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/python/Python-3.5.0/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/main.py", line 285, in main
    pipeline.execute()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 245, in execute
    self.convert_vcf()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 88, in convert_vcf
    lib.convert_vcf.main(convert_params)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/convert_vcf.py", line 184, in main
    for entry in vcf_reader:
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/vcf/parser.py", line 586, in __next__
    samples = self._parse_samples(row[9:], fmt, record)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/vcf/parser.py", line 483, in _parse_samples
    sampdat[i] = float(vals)
ValueError: could not convert string to float: '16&16'

[011202.vcf.zip](https://github.com/griffithlab/pVAC-Seq/files/776278/011202.vcf.zip)

**Comment by susannasiebert** [comment]
It looks like your VCF doesn't contain any FORMAT field headers. Thus, the VCF parser pVAC-Seq uses doesn't know how to parse this field correctly. It looks like maybe by default it assumes these fields are floats and for this specific field that conversion failed. Please try adding the appropriate FORMAT field headers with the correct types and see if that fixes the problem.

**Comment by susannasiebert** [comment]
Did adding the needed FORMAT fields work for you? Can I resolve this issue?
