### ISSUE TITLE
NetChop : ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVAC-Seq#270]
Waiting for results from NetChop...
Traceback (most recent call last):
  File "/software/python/Python-3.5.0/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/main.py", line 285, in main
    pipeline.execute()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 277, in execute
    self.net_chop()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 226, in net_chop
    str(self.net_chop_threshold)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/net_chop.py", line 115, in main
    max_cleavage_score = max(cleavage_scores.items(), key=lambda x: x[1])
ValueError: max() arg is an empty sequence

Is this a bug....???

**Comment by susannasiebert** [comment]
Yes. This issue was first reported in issue #260 and addressed in pull request #266. The fix will be available in the next release.

**Comment by susannasiebert** [comment]
The newest release (4.0.7) fixes this issue. Please upgrade your install of pVAC-Seq and let me know if that fixes it for you.
