### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by kylec** [griffithlab/pVAC-Seq#278]
I'm running 4.0.7 and encounter the following issue.

pvacseq run H_G13-H_G16.vep.vcf H_G13 HLA-A*25:01,HLA-A*11:01,HLA-B*18:01,HLA-B*35:01,HLA-C*04:01,HLA-C*12:03 NetMHCpan H_G13-result -e 8,9,10,11 --iedb-install-directory /rsrch2/ccp_rsch/kchang3/software/IEDB/
...
Generating Variant Peptide FASTA and Key Files - Entries 7601-7696
Completed
Processing entries for Allele HLA-A*11:01 and Epitope Length 8 - Entries 1-200
Running IEDB on Allele HLA-A*11:01 and Epitope Length 8 with Method NetMHCpan - Entries 1-200
Traceback (most recent call last):
  File "/rsrch2/ccp_rsch/kchang3/software/python3venv/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/rsrch2/ccp_rsch/kchang3/software/python3venv/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/rsrch2/ccp_rsch/kchang3/software/python3venv/lib/python3.5/site-packages/pvacseq/lib/main.py", line 285, in main
    pipeline.execute()
  File "/rsrch2/ccp_rsch/kchang3/software/python3venv/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 256, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/rsrch2/ccp_rsch/kchang3/software/python3venv/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 378, in call_iedb_and_parse_outputs
    '-e', self.iedb_executable,
  File "/rsrch2/ccp_rsch/kchang3/software/python3venv/lib/python3.5/site-packages/pvacseq/lib/call_iedb.py", line 61, in main
    response_text = filter_response(response.stdout)
  File "/rsrch2/ccp_rsch/kchang3/software/python3venv/lib/python3.5/site-packages/pvacseq/lib/call_iedb.py", line 15, in filter_response
    lines = response_text.split("\n")
TypeError: a bytes-like object is required, not 'str'
[vcf.zip](https://github.com/griffithlab/pVAC-Seq/files/814642/vcf.zip)

**Comment by susannasiebert** [comment]
@kylec A fix for this bug is in PR #279 and will be pushed out as soon as possible.

**Comment by susannasiebert** [comment]
A new release (4.0.8) is now available that should fix this issue. Please upgrade to the latest version and let me know if that fixes it for you.

**Comment by kylec** [comment]
It works thank you.
