### ISSUE TITLE
The two methods NetMHCpan and NetMHC produced different outputs, number of peptides not the same

### ISSUE THREAD

**Issue by patidarr** [griffithlab/pVAC-Seq#282]
I ran the pipeline successfully on >100 samples so far and got following error on one sample:
Command I ran
`       pvacseq run --iedb-install-directory /home/patidarr/IEDB/ -e 8,9,10,11 --fasta-size=200 CL0086/20161118/CL0086_T1D_E/NeoAntigen/CL0086_T1D_E.final.vcf CL0086_T1D_E ${allele} {NNalign,NetM
HC,NetMHCIIpan,NetMHCcons,NetMHCpan,PickPocket,SMM,SMMPMBEC,SMMalign} CL0086/20161118/CL0086_T1D_E/NeoAntigen/
`

Error I got:

`The two methods NetMHCpan and NetMHC produced different outputs, number of peptides not the same
Traceback (most recent call last):
  File "/home/patidarr/IEDB/mhc_i/src/predict_binding.py", line 378, in <module>
    Prediction().main()
  File "/home/patidarr/IEDB/mhc_i/src/predict_binding.py", line 370, in main
    self.commandline_input(args)
  File "/home/patidarr/IEDB/mhc_i/src/predict_binding.py", line 73, in commandline_input
    mhc_scores = mhc_predictor.predict(input.input_protein.as_amino_acid_text())
  File "/home/patidarr/IEDB/mhc_i/src/seqpredictor.py", line 1037, in predict
    scores.append(predictor.predict_sequence(sequence,pred))
  File "/home/patidarr/IEDB/mhc_i/src/seqpredictor.py", line 527, in predict_sequence
    scores = self.predict_peptide_list(peptide_list)
  File "/home/patidarr/IEDB/mhc_i/src/seqpredictor.py", line 591, in predict_peptide_list
    raise PredictorError(msg)
util.PredictorError
Traceback (most recent call last):
  File "/apps/pVAC-Seq/4.0.6/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/lib/main.py", line 285, in main
    pipeline.execute()
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 253, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 367, in call_iedb_and_parse_outputs
    '-e', self.iedb_executable,
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/lib/call_iedb.py", line 51, in main
    response = run(prediction_class_object.iedb_executable_params(args), stdout=PIPE, check=True)
  File "/apps/Python/3.5.0/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python2.7', '/home/patidarr/IEDB/mhc_i/src/predict_binding.py', 'netmhccons', 'HLA-A*02:01', '9', '/projects/Clinomics/ProcessedResults/CL0086/20161118/CL0086_T1D_E/NeoAntigen/MHC_Class_I/tmp/CL0086_T1D_E_21.fa.split_601-800']' returned non-zero exit status 1
Error in job pVACseq while creating output file CL0086/20161118/CL0086_T1D_E/NeoAntigen/MHC_Class_I/CL0086_T1D_E.final.tsv.
RuleException:
CalledProcessError in line 84 of /projects/Clinomics/Tools/ngs_pipeline/ruleBook/NeoAntigen.snakefile:
Command '
`

**Comment by susannasiebert** [comment]
This seems to be an error with IEDB. Please put in a ticket with their help desk at help.iedb.org.

**Comment by patidarr** [comment]
But when I ran following command I got the result.
`[patidarr@login01 ProcessedResults]$ python2.7 /home/patidarr/IEDB/mhc_i/src/predict_binding.py netmhccons HLA-A*02:01 9 /projects/Clinomics/ProcessedResults/CL0086/20161118/CL0086_T1D_E/NeoAntigen/MHC_Class_I/tmp/CL0086_T1D_E_21.fa.split_601-800`

allele  seq_num start   end     length  peptide ic50    rank
HLA-A*02:01     35      2       10      9       FIMELLKTL       9.34    0.5
HLA-A*02:01     36      2       10      9       FIMELLKTL       9.34    0.5
HLA-A*02:01     56      4       12      9       GLWYVMQMV       12.44   0.6
HLA-A*02:01     55      4       12      9       GLWYVMQVV       18.87   0.8
HLA-A*02:01     55      7       15      9       YVMQVVSQL       31.04   1.1
HLA-A*02:01     41      9       17      9       NLMSHAQEL       33.12   1.2
HLA-A*02:01     41      10      18      9       LMSHAQELV       35.92   1.2

**Comment by susannasiebert** [comment]
I'm not sure why that would be. The only difference is that pVAC-Seq calls the same command you did from inside a python script. When you call the IEDB script standalone, are you doing so from a python 3.5 environment? Are you using snakemake for both calls?

Nevertheless, the error gets thrown by IEDB so they would be the ones to ask why one way of calling their software works for you and the other doesn't. Therefore, I still recommend putting in a ticket with IEDB with the stack trace and the input fasta and mentioning that running it standalone works.
