### ISSUE TITLE
parsing error in match_wildtype_and_mutant_entry_for_missense

### ISSUE THREAD

**Issue by chrisamiller** [griffithlab/pVAC-Seq#290]
I'm splitting my files out to the cluster, and I'm seeing this same error on a bunch of different data. Here are steps to replicate the error on a test data set. Feel free to mess around with this data - I have another copy.

```
$ pvacseq  -v
4.0.8
$ cd /gscuser/cmiller/tmp/pvac
$ pvacseq run -b 500 -c 1 -e 8,9,10,11 --iedb-install-directory /gscmnt/gc2502/griffithlab/yafeng/ xat.vcf pt2 'HLA-A*01:01,HLA-A*02:01,HLA-B*51:01,HLA-B*57:01,HLA-C*02:02,HLA-C*06:02' {NetMHC,NetMHCpan,PickPocket,SMM,SMMPMBEC} xat.out
Executing MHC Class I predictions
Converting VCF to TSV
TSV file already exists. Skipping.
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-21
Split TSV file for Entries 1-21 already exists. Skipping.
Completed
Generating Variant Peptide FASTA and Key Files
Split FASTA file for Entries 1-42 already exists. Skipping.
Completed
Processing entries for Allele HLA-A*01:01 and Epitope Length 8 - Entries 1-42
IEDB file for Allele HLA-A*01:01 and Epitope Length 8 with Method NetMHC (Entries 1-42) already exists. Skipping.
IEDB file for Allele HLA-A*01:01 and Epitope Length 8 with Method NetMHCpan (Entries 1-42) already exists. Skipping.
IEDB file for Allele HLA-A*01:01 and Epitope Length 8 with Method PickPocket (Entries 1-42) already exists. Skipping.
IEDB file for Allele HLA-A*01:01 and Epitope Length 8 with Method SMM (Entries 1-42) already exists. Skipping.
IEDB file for Allele HLA-A*01:01 and Epitope Length 8 with Method SMMPMBEC (Entries 1-42) already exists. Skipping.
Parsed Output File for Allele HLA-A*01:01 and Epitope Length 8 (Entries 1-42) already exists. Skipping
Processing entries for Allele HLA-A*01:01 and Epitope Length 9 - Entries 1-42
IEDB file for Allele HLA-A*01:01 and Epitope Length 9 with Method NetMHC (Entries 1-42) already exists. Skipping.
IEDB file for Allele HLA-A*01:01 and Epitope Length 9 with Method NetMHCpan (Entries 1-42) already exists. Skipping.
IEDB file for Allele HLA-A*01:01 and Epitope Length 9 with Method PickPocket (Entries 1-42) already exists. Skipping.
IEDB file for Allele HLA-A*01:01 and Epitope Length 9 with Method SMM (Entries 1-42) already exists. Skipping.
IEDB file for Allele HLA-A*01:01 and Epitope Length 9 with Method SMMPMBEC (Entries 1-42) already exists. Skipping.
Parsed Output File for Allele HLA-A*01:01 and Epitope Length 9 (Entries 1-42) already exists. Skipping
Processing entries for Allele HLA-A*01:01 and Epitope Length 10 - Entries 1-42
IEDB file for Allele HLA-A*01:01 and Epitope Length 10 with Method NetMHC (Entries 1-42) already exists. Skipping.
IEDB file for Allele HLA-A*01:01 and Epitope Length 10 with Method NetMHCpan (Entries 1-42) already exists. Skipping.
IEDB file for Allele HLA-A*01:01 and Epitope Length 10 with Method PickPocket (Entries 1-42) already exists. Skipping.
IEDB file for Allele HLA-A*01:01 and Epitope Length 10 with Method SMM (Entries 1-42) already exists. Skipping.
IEDB file for Allele HLA-A*01:01 and Epitope Length 10 with Method SMMPMBEC (Entries 1-42) already exists. Skipping.
Parsing IEDB Output for Allele HLA-A*01:01 and Epitope Length 10 - Entries 1-42
Traceback (most recent call last):
  File "/gscuser/cmiller/usr/miniconda2/envs/python3/bin/pvacseq", line 9, in <module>
    load_entry_point('pvacseq', 'console_scripts', 'pvacseq')()
  File "/gscuser/cmiller/src/pvacseq/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/gscuser/cmiller/src/pvacseq/pvacseq/lib/main.py", line 285, in main
    pipeline.execute()
  File "/gscuser/cmiller/src/pvacseq/pvacseq/lib/pipeline.py", line 256, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/gscuser/cmiller/src/pvacseq/pvacseq/lib/pipeline.py", line 403, in call_iedb_and_parse_outputs
    lib.parse_output.main(params)
  File "/gscuser/cmiller/src/pvacseq/pvacseq/lib/parse_output.py", line 449, in main
    iedb_results = process_input_iedb_file(args.input_iedb_files, tsv_entries, args.key_file, args.top_result_per_mutation, args.top_score_metric)
  File "/gscuser/cmiller/src/pvacseq/pvacseq/lib/parse_output.py", line 361, in process_input_iedb_file
    iedb_results              = parse_iedb_file(input_iedb_files, tsv_entries, key_file)
  File "/gscuser/cmiller/src/pvacseq/pvacseq/lib/parse_output.py", line 291, in parse_iedb_file
    return match_wildtype_and_mutant_entries(iedb_results, wt_iedb_results)
  File "/gscuser/cmiller/src/pvacseq/pvacseq/lib/parse_output.py", line 232, in match_wildtype_and_mutant_entries
    match_wildtype_and_mutant_entry_for_missense(result, mt_position, wt_results, previous_result)
  File "/gscuser/cmiller/src/pvacseq/pvacseq/lib/parse_output.py", line 70, in match_wildtype_and_mutant_entry_for_missense
    previous_mutation_position = previous_result['mutation_position']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by chrisamiller** [comment]
Closed by https://github.com/griffithlab/pVAC-Seq/pull/291 .  Thanks!
