### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by diazlab** [griffithlab/pVAC-Seq#299]
Hi, any insight into the following install error, Windows 10, python 3.5?

C:\Users\aaron\AppData\Local\Temp>pip install pvacseq
Collecting pvacseq
  Using cached pvacseq-4.0.9-py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "c:\users\aaron\appdata\local\programs\python\python35-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\aaron\appdata\local\programs\python\python35-32\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\aaron\appdata\local\programs\python\python35-32\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\aaron\appdata\local\programs\python\python35-32\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\users\aaron\appdata\local\programs\python\python35-32\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "c:\users\aaron\appdata\local\programs\python\python35-32\lib\site-packages\pip\download.py", line 663, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "c:\users\aaron\appdata\local\programs\python\python35-32\lib\site-packages\pip\utils\__init__.py", line 599, in unpack_file
    flatten=not filename.endswith('.whl')
  File "c:\users\aaron\appdata\local\programs\python\python35-32\lib\site-packages\pip\utils\__init__.py", line 499, in unzip_file
    fp = open(fn, 'wb')
OSError: [Errno 22] Invalid argument: 'C:\\Users\\aaron\\AppData\\Local\\Temp\\pip-build-1dqki7ah\\pvacseq\\pvacseq/example_data/MHC_Class_I/tmp/Test.HLA-E*01:01.9.parsed.tsv_1-48'

**Comment by susannasiebert** [comment]
pVAC-Seq is only compatible with Linux and Mac OS X.

**Comment by susannasiebert** [comment]
You could try using bash on ubuntu on Windows 10: https://msdn.microsoft.com/en-us/commandline/wsl/about. I'm not sure if that would work without further modifications. We haven't tested it.
