### ISSUE TITLE
KeyError: 'WildtypeProtein'

### ISSUE THREAD

**Issue by xuxue1986** [griffithlab/pVAC-Seq#301]
Hi,

I meet a new error when I used pvac-seq. 
This is my process:

**pvacseq run TUMOR.vcf test1 HLA-G01:09,HLA-E01:01,H2-IAb NetMHC PickPocket NNalign /home/xuexu/Documents/melanoma_project/neoantigene/IEDB/pvacseq-4.1.0b0/pvacseq/example_data/result4 -e 9,10**

My TUMOR.vcf originally consists of tumor and normal samples, and I used vcftools to separate them. Then I used pvacseq, and encountered this error.

The result are: 
**Executing MHC Class I predictions
Converting VCF to TSV
Traceback (most recent call last):
File "/home/xuexu/miniconda2/envs/snakes/bin/pvacseq", line 11, in
sys.exit(main())
File "/home/xuexu/miniconda2/envs/snakes/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
args[0].func.main(args[1])
File "/home/xuexu/miniconda2/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/main.py", line 291, in main
pipeline.execute()
File "/home/xuexu/miniconda2/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 292, in execute
self.convert_vcf()
File "/home/xuexu/miniconda2/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 133, in convert_vcf
lib.convert_vcf.main(convert_params)
File "/home/xuexu/miniconda2/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/convert_vcf.py", line 264, in main
'wildtype_amino_acid_sequence' : transcript['WildtypeProtein'],
KeyError: 'WildtypeProtein'**

I donot know what the error is

**Comment by susannasiebert** [comment]
After you split your VCF did you annotate it with VEP? If so, did you download the plugins before running VEP (pvacseq install_vep_plugins)?

**Comment by xuxue1986** [comment]
Oh, I just split the VEP-processed vcf file. Now, I am split raw vcf file first ,and then try

**Comment by susannasiebert** [comment]
Sounds good. Please let me know if that fixes that problem. I will keep this issue open until then.

**Comment by xuxue1986** [comment]
Hi,
Your suggestion is right! I should first split the raw file, and then employ vep to process the file, and finally use pvac-seq. 
Thank you very much
