### ISSUE TITLE
Running NetMHCcons

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVAC-Seq#304]
Hey Guys,
How we can manage two python versions, running together. Facing this error with NetMHCcons, requires 2.7 and pVAC running on 3.5.

**********
Executing MHC Class I predictions
Converting VCF to TSV
TSV file already exists. Skipping.
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-139
Split TSV file for Entries 1-139 already exists. Skipping.
Completed
Generating Variant Peptide FASTA and Key Files
Split FASTA file for Entries 1-278 already exists. Skipping.
Completed
Processing entries for Allele HLA-A*02:01 and Epitope Length 8 - Entries 1-278
Running IEDB on Allele HLA-A*02:01 and Epitope Length 8 with Method NetMHCcons - Entries 1-278
File "/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/method/netMHCcons-1.1/bin/pseudofind", line 141
    print "#\t"+reffilename
              ^
SyntaxError: Missing parentheses in call to 'print'
  File "/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/method/netMHC-3.4/netMHC", line 112
    print "### Alleles with ANN predictors:"
                                           ^
SyntaxError: Missing parentheses in call to 'print'
The two methods NetMHCpan and NetMHC produced different outputs, number of peptides not the same
Traceback (most recent call last):
  File "/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/src/predict_binding.py", line 380, in <module>
    Prediction().main()
  File "/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/src/predict_binding.py", line 372, in main
    self.commandline_input(args)
  File "/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/src/predict_binding.py", line 73, in commandline_input
    mhc_scores = mhc_predictor.predict(input.input_protein.as_amino_acid_text())
  File "/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/src/seqpredictor.py", line 1037, in predict
    scores.append(predictor.predict_sequence(sequence,pred))
  File "/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/src/seqpredictor.py", line 527, in predict_sequence
    scores = self.predict_peptide_list(peptide_list)
  File "/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/src/seqpredictor.py", line 591, in predict_peptide_list
    raise PredictorError(msg)
util.PredictorError
Traceback (most recent call last):
  File "/software/python/Python-3.5.0/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/main.py", line 291, in main
    pipeline.execute()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 300, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 422, in call_iedb_and_parse_outputs
    '-e', self.iedb_executable,
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/call_iedb.py", line 60, in main
    response = run(prediction_class_object.iedb_executable_params(args), stdout=PIPE, check=True)
  File "/software/python/Python-3.5.0/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python2.7', '/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/src/predict_binding.py', 'netmhccons', 'HLA-A*02:01', '8', '/working/genomeinfo/share/venkatA/Analysis/Neoantigens/NetMHCcons_Clin88_tes/MHC_Class_I/tmp/19351_SCC11-0270_502265_T_21.fa.split_1-278']' returned non-zero exit status 1
***********************************

**Comment by chrisamiller** [comment]
We recommend conda for installing and managing multiple versions of python.
https://conda.io/docs/get-started.html
