### ISSUE TITLE
NetMHCcons error

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVAC-Seq#305]
Have you seen such error before? 

The two methods NetMHCpan and NetMHC produced different outputs, number of peptides not the same
Traceback (most recent call last):
  File "/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/src/predict_binding.py", line 380, in <module>
    Prediction().main()
  File "/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/src/predict_binding.py", line 372, in main
    self.commandline_input(args)
  File "/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/src/predict_binding.py", line 73, in commandline_input
    mhc_scores = mhc_predictor.predict(input.input_protein.as_amino_acid_text())
  File "/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/src/seqpredictor.py", line 1037, in predict
    scores.append(predictor.predict_sequence(sequence,pred))
  File "/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/src/seqpredictor.py", line 527, in predict_sequence
    scores = self.predict_peptide_list(peptide_list)
  File "/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/src/seqpredictor.py", line 591, in predict_peptide_list
    raise PredictorError(msg)
util.PredictorError
Traceback (most recent call last):
  File "/software/python/Python-3.5.0/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/main.py", line 291, in main
    pipeline.execute()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 300, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 422, in call_iedb_and_parse_outputs
    '-e', self.iedb_executable,
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/call_iedb.py", line 60, in main
    response = run(prediction_class_object.iedb_executable_params(args), stdout=PIPE, check=True)
  File "/software/python/Python-3.5.0/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python2.7', '/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/src/predict_binding.py', 'netmhccons', 'HLA-A*02:01', '9', '/working/genomeinfo/share/temp/venkatA/Analysis/Neoantigens/NetMHCcons_Clin88/39658_SCC14-0131_502426_T_HLA/MHC_Class_I/tmp/39658_SCC14-0131_502426_T_HLA_21.fa.split_1-146']' returned non-zero exit status 1

**Comment by susannasiebert** [comment]
The user in [this issue](https://github.com/griffithlab/pVAC-Seq/issues/282) reported the same error but we weren't able to determine why this error was occurring. We recommend putting in an error report with IEDB since it is their software throwing the error. We would be interested to hear their reply in case there is something we need to change on our end.
