### ISSUE TITLE
Is this related to compund SNP?

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVAC-Seq#316]
Traceback (most recent call last):
  File "/software/python/Python-3.5.0/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/main.py", line 291, in main
    pipeline.execute()
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 299, in execute
    self.generate_fasta(chunks)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 375, in generate_fasta
    lib.generate_fasta.main(generate_fasta_params)
  File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/generate_fasta.py", line 111, in main
    wildtype_amino_acid, mutant_amino_acid = line['amino_acid_change'].split('/')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by susannasiebert** [comment]
This looks like a SNP edge case that's currently not handled by pVAC-Seq. Would you be able to narrow down the variant that is causing this error and share it with us (or some dummy variant that is causing this same error)?

**Comment by susannasiebert** [comment]
@venkataddala We're still interested in fixing this issue but we well need a test case to reproduce this on our end.

**Comment by susannasiebert** [comment]
@venkataddala We are transitioning the pVACseq issue tracking to the [pVACtools repository](https://github.com/griffithlab/pVACtools). If you would still like assistance with this error, please make a new issue there.
